name: Python linting

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/linter/requirements.txt
      
    - name: Lint with Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./ --config=config/linter/flake8.cfg --exit-zero > linting_flake8.txt
        cat linting_flake8.txt

        total_errors="$(tail -1 linting_flake8.txt)"
        threshold=10

        if [[  $total_errors -gt $threshold ]];
        then
            echo "Too many errors"
            exit 1
        fi

    - name: Upload flake8 results
      uses: actions/upload-artifact@v2
      with:
        name: linting_flake8
        path: linting_flake8.txt
